package com.lac.xaboa.db.model;

import com.google.gson.annotations.Expose;
// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table FLOW.
 */
public class Flow implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	
	@Expose
    private Long _id;
	@Expose
    private String id;
	@Expose
    private String doc_no;
	@Expose
    private String name;
	@Expose
    private String content;
	@Expose
    private String confirm;
	@Expose
    private String confirm_name;
	@Expose
    private String consult;
	@Expose
    private String consult_name;
	@Expose
    private String refer;
	@Expose
    private String refer_name;
	@Expose
    private String type;
	@Expose
    private String add_file;
	@Expose
    private String user_id;
	@Expose
    private String emp_no;
	@Expose
    private String user_name;
	@Expose
    private String dept_id;
	@Expose
    private String dept_name;
	@Expose
    private String create_date;
	@Expose
    private String create_time;
	@Expose
    private String update_time;
	@Expose
    private String step;
	@Expose
    private String is_del;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Flow() {
    }

    public Flow(Long _id) {
        this._id = _id;
    }

    public Flow(Long _id, String id, String doc_no, String name, String content, String confirm, String confirm_name, String consult, String consult_name, String refer, String refer_name, String type, String add_file, String user_id, String emp_no, String user_name, String dept_id, String dept_name, String create_date, String create_time, String update_time, String step, String is_del) {
        this._id = _id;
        this.id = id;
        this.doc_no = doc_no;
        this.name = name;
        this.content = content;
        this.confirm = confirm;
        this.confirm_name = confirm_name;
        this.consult = consult;
        this.consult_name = consult_name;
        this.refer = refer;
        this.refer_name = refer_name;
        this.type = type;
        this.add_file = add_file;
        this.user_id = user_id;
        this.emp_no = emp_no;
        this.user_name = user_name;
        this.dept_id = dept_id;
        this.dept_name = dept_name;
        this.create_date = create_date;
        this.create_time = create_time;
        this.update_time = update_time;
        this.step = step;
        this.is_del = is_del;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getDoc_no() {
        return doc_no;
    }

    public void setDoc_no(String doc_no) {
        this.doc_no = doc_no;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getConfirm() {
        return confirm;
    }

    public void setConfirm(String confirm) {
        this.confirm = confirm;
    }

    public String getConfirm_name() {
        return confirm_name;
    }

    public void setConfirm_name(String confirm_name) {
        this.confirm_name = confirm_name;
    }

    public String getConsult() {
        return consult;
    }

    public void setConsult(String consult) {
        this.consult = consult;
    }

    public String getConsult_name() {
        return consult_name;
    }

    public void setConsult_name(String consult_name) {
        this.consult_name = consult_name;
    }

    public String getRefer() {
        return refer;
    }

    public void setRefer(String refer) {
        this.refer = refer;
    }

    public String getRefer_name() {
        return refer_name;
    }

    public void setRefer_name(String refer_name) {
        this.refer_name = refer_name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getAdd_file() {
        return add_file;
    }

    public void setAdd_file(String add_file) {
        this.add_file = add_file;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getEmp_no() {
        return emp_no;
    }

    public void setEmp_no(String emp_no) {
        this.emp_no = emp_no;
    }

    public String getUser_name() {
        return user_name;
    }

    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    public String getDept_id() {
        return dept_id;
    }

    public void setDept_id(String dept_id) {
        this.dept_id = dept_id;
    }

    public String getDept_name() {
        return dept_name;
    }

    public void setDept_name(String dept_name) {
        this.dept_name = dept_name;
    }

    public String getCreate_date() {
        return create_date;
    }

    public void setCreate_date(String create_date) {
        this.create_date = create_date;
    }

    public String getCreate_time() {
        return create_time;
    }

    public void setCreate_time(String create_time) {
        this.create_time = create_time;
    }

    public String getUpdate_time() {
        return update_time;
    }

    public void setUpdate_time(String update_time) {
        this.update_time = update_time;
    }

    public String getStep() {
        return step;
    }

    public void setStep(String step) {
        this.step = step;
    }

    public String getIs_del() {
        return is_del;
    }

    public void setIs_del(String is_del) {
        this.is_del = is_del;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
