package com.lac.xaboa.db.model;

import com.google.gson.annotations.Expose;
// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table FLOW_LOG.
 */
public class FlowLog implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	
	@Expose
    private Long _id;
	@Expose
    private String id;
	@Expose
    private String flow_id;
	@Expose
    private String emp_no;
	@Expose
    private String user_id;
	@Expose
    private String user_name;
	@Expose
    private String step;
	@Expose
    private String result;
	@Expose
    private String create_time;
	@Expose
    private String update_time;
	@Expose
    private String comment;
	@Expose
    private String is_read;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public FlowLog() {
    }

    public FlowLog(Long _id) {
        this._id = _id;
    }

    public FlowLog(Long _id, String id, String flow_id, String emp_no, String user_id, String user_name, String step, String result, String create_time, String update_time, String comment, String is_read) {
        this._id = _id;
        this.id = id;
        this.flow_id = flow_id;
        this.emp_no = emp_no;
        this.user_id = user_id;
        this.user_name = user_name;
        this.step = step;
        this.result = result;
        this.create_time = create_time;
        this.update_time = update_time;
        this.comment = comment;
        this.is_read = is_read;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getFlow_id() {
        return flow_id;
    }

    public void setFlow_id(String flow_id) {
        this.flow_id = flow_id;
    }

    public String getEmp_no() {
        return emp_no;
    }

    public void setEmp_no(String emp_no) {
        this.emp_no = emp_no;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getUser_name() {
        return user_name;
    }

    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    public String getStep() {
        return step;
    }

    public void setStep(String step) {
        this.step = step;
    }

    public String getResult() {
        return result;
    }

    public void setResult(String result) {
        this.result = result;
    }

    public String getCreate_time() {
        return create_time;
    }

    public void setCreate_time(String create_time) {
        this.create_time = create_time;
    }

    public String getUpdate_time() {
        return update_time;
    }

    public void setUpdate_time(String update_time) {
        this.update_time = update_time;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getIs_read() {
        return is_read;
    }

    public void setIs_read(String is_read) {
        this.is_read = is_read;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
