package com.lac.xaboa.db.model;

import com.google.gson.annotations.Expose;
// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table MEMBER.
 */
public class Member implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	

    private Long _id;
	@Expose
    private String id;
	@Expose
    private String emp_no;
	@Expose
    private String name;
	@Expose
    private String letter;
	@Expose
    private String password;
	@Expose
    private String dept_id;
	@Expose
    private String position_id;
	@Expose
    private String rank_id;
	@Expose
    private String sex;
	@Expose
    private String birthday;
	@Expose
    private String last_login_ip;
	@Expose
    private String login_count;
	@Expose
    private String pic;
	@Expose
    private String email;
	@Expose
    private String duty;
	@Expose
    private String office_tel;
	@Expose
    private String mobile_tel;
	@Expose
    private String create_time;
	@Expose
    private String update_time;
	@Expose
    private String is_del;
	@Expose
    private String openid;
	@Expose
    private String westatus;
	@Expose
    private String error;
	@Expose
    private String emp_randid;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Member() {
    }

    public Member(Long _id) {
        this._id = _id;
    }

    public Member(Long _id, String id, String emp_no, String name, String letter, String password, String dept_id, String position_id, String rank_id, String sex, String birthday, String last_login_ip, String login_count, String pic, String email, String duty, String office_tel, String mobile_tel, String create_time, String update_time, String is_del, String openid, String westatus, String error, String emp_randid) {
        this._id = _id;
        this.id = id;
        this.emp_no = emp_no;
        this.name = name;
        this.letter = letter;
        this.password = password;
        this.dept_id = dept_id;
        this.position_id = position_id;
        this.rank_id = rank_id;
        this.sex = sex;
        this.birthday = birthday;
        this.last_login_ip = last_login_ip;
        this.login_count = login_count;
        this.pic = pic;
        this.email = email;
        this.duty = duty;
        this.office_tel = office_tel;
        this.mobile_tel = mobile_tel;
        this.create_time = create_time;
        this.update_time = update_time;
        this.is_del = is_del;
        this.openid = openid;
        this.westatus = westatus;
        this.error = error;
        this.emp_randid = emp_randid;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getEmp_no() {
        return emp_no;
    }

    public void setEmp_no(String emp_no) {
        this.emp_no = emp_no;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLetter() {
        return letter;
    }

    public void setLetter(String letter) {
        this.letter = letter;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getDept_id() {
        return dept_id;
    }

    public void setDept_id(String dept_id) {
        this.dept_id = dept_id;
    }

    public String getPosition_id() {
        return position_id;
    }

    public void setPosition_id(String position_id) {
        this.position_id = position_id;
    }

    public String getRank_id() {
        return rank_id;
    }

    public void setRank_id(String rank_id) {
        this.rank_id = rank_id;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getLast_login_ip() {
        return last_login_ip;
    }

    public void setLast_login_ip(String last_login_ip) {
        this.last_login_ip = last_login_ip;
    }

    public String getLogin_count() {
        return login_count;
    }

    public void setLogin_count(String login_count) {
        this.login_count = login_count;
    }

    public String getPic() {
        return pic;
    }

    public void setPic(String pic) {
        this.pic = pic;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getDuty() {
        return duty;
    }

    public void setDuty(String duty) {
        this.duty = duty;
    }

    public String getOffice_tel() {
        return office_tel;
    }

    public void setOffice_tel(String office_tel) {
        this.office_tel = office_tel;
    }

    public String getMobile_tel() {
        return mobile_tel;
    }

    public void setMobile_tel(String mobile_tel) {
        this.mobile_tel = mobile_tel;
    }

    public String getCreate_time() {
        return create_time;
    }

    public void setCreate_time(String create_time) {
        this.create_time = create_time;
    }

    public String getUpdate_time() {
        return update_time;
    }

    public void setUpdate_time(String update_time) {
        this.update_time = update_time;
    }

    public String getIs_del() {
        return is_del;
    }

    public void setIs_del(String is_del) {
        this.is_del = is_del;
    }

    public String getOpenid() {
        return openid;
    }

    public void setOpenid(String openid) {
        this.openid = openid;
    }

    public String getWestatus() {
        return westatus;
    }

    public void setWestatus(String westatus) {
        this.westatus = westatus;
    }

    public String getError() {
        return error;
    }

    public void setError(String error) {
        this.error = error;
    }

    public String getEmp_randid() {
        return emp_randid;
    }

    public void setEmp_randid(String emp_randid) {
        this.emp_randid = emp_randid;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
