package com.lac.xaboa.db.model;

import com.google.gson.annotations.Expose;
// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table NOTICE.
 */
public class Notice implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	
	@Expose
    private Long _id;
	@Expose
    private String id;
	@Expose
    private String notice_no;
	@Expose
    private String name;
	@Expose
    private String content;
	@Expose
    private String folder;
	@Expose
    private String add_file;
	@Expose
    private String user_id;
	@Expose
    private String user_name;
	@Expose
    private String create_time;
	@Expose
    private String update_time;
	@Expose
    private String is_del;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Notice() {
    }

    public Notice(Long _id) {
        this._id = _id;
    }

    public Notice(Long _id, String id, String notice_no, String name, String content, String folder, String add_file, String user_id, String user_name, String create_time, String update_time, String is_del) {
        this._id = _id;
        this.id = id;
        this.notice_no = notice_no;
        this.name = name;
        this.content = content;
        this.folder = folder;
        this.add_file = add_file;
        this.user_id = user_id;
        this.user_name = user_name;
        this.create_time = create_time;
        this.update_time = update_time;
        this.is_del = is_del;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getNotice_no() {
        return notice_no;
    }

    public void setNotice_no(String notice_no) {
        this.notice_no = notice_no;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getFolder() {
        return folder;
    }

    public void setFolder(String folder) {
        this.folder = folder;
    }

    public String getAdd_file() {
        return add_file;
    }

    public void setAdd_file(String add_file) {
        this.add_file = add_file;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getUser_name() {
        return user_name;
    }

    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    public String getCreate_time() {
        return create_time;
    }

    public void setCreate_time(String create_time) {
        this.create_time = create_time;
    }

    public String getUpdate_time() {
        return update_time;
    }

    public void setUpdate_time(String update_time) {
        this.update_time = update_time;
    }

    public String getIs_del() {
        return is_del;
    }

    public void setIs_del(String is_del) {
        this.is_del = is_del;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
