package com.lac.xaboa.db.model;

import com.google.gson.annotations.Expose;
// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table PUSH_LOG.
 */
public class PushLog implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	
	@Expose
    private Long _id;
	@Expose
    private String id;
	@Expose
    private String pushtype;
	@Expose
    private String operate;
	@Expose
    private String tablename;
	@Expose
    private String userid;
    @Expose
    private String dataid;

    private String status;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PushLog() {
    }

    public PushLog(Long _id) {
        this._id = _id;
    }

    public PushLog(Long _id, String id, String pushtype, String operate, String tablename, String userid, String dataid, String status) {
        this._id = _id;
        this.id = id;
        this.pushtype = pushtype;
        this.operate = operate;
        this.tablename = tablename;
        this.userid = userid;
        this.dataid = dataid;
        this.status = status;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getPushtype() {
        return pushtype;
    }

    public void setPushtype(String pushtype) {
        this.pushtype = pushtype;
    }

    public String getOperate() {
        return operate;
    }

    public void setOperate(String operate) {
        this.operate = operate;
    }

    public String getTablename() {
        return tablename;
    }

    public void setTablename(String tablename) {
        this.tablename = tablename;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getDataid() {
        return dataid;
    }

    public void setDataid(String dataid) {
        this.dataid = dataid;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
